SECTION "Pics 1", ROMX

IF GEN_2_GRAPHICS
MoltresPicFront::    INCBIN "gfx/pokemon/gsfront/moltres.pic"
MoltresPicBack::     INCBIN "gfx/pokemon/gsback/moltresb.pic"

TentacoolPicFront::  INCBIN "gfx/pokemon/gsfront/tentacool.pic"
TentacoolPicBack::   INCBIN "gfx/pokemon/gsback/tentacoolb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/gsfront/scyther.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/gsback/scytherb.pic"
StaryuPicFront::     INCBIN "gfx/pokemon/gsfront/staryu.pic"
StaryuPicBack::      INCBIN "gfx/pokemon/gsback/staryub.pic"
BlastoisePicFront::  INCBIN "gfx/pokemon/gsfront/blastoise.pic"
BlastoisePicBack::   INCBIN "gfx/pokemon/gsback/blastoiseb.pic"
PinsirPicFront::     INCBIN "gfx/pokemon/gsfront/pinsir.pic"
PinsirPicBack::      INCBIN "gfx/pokemon/gsback/pinsirb.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/gsfront/tangela.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/gsback/tangelab.pic"

JolteonPicFront::    INCBIN "gfx/pokemon/gsfront/jolteon.pic"
JolteonPicBack::     INCBIN "gfx/pokemon/gsback/jolteonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/gsfront/vaporeon.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/gsback/vaporeonb.pic"
MachopPicFront::     INCBIN "gfx/pokemon/gsfront/machop.pic"
MachopPicBack::      INCBIN "gfx/pokemon/gsback/machopb.pic"
ZubatPicFront::      INCBIN "gfx/pokemon/gsfront/zubat.pic"
ZubatPicBack::       INCBIN "gfx/pokemon/gsback/zubatb.pic"
EkansPicFront::      INCBIN "gfx/pokemon/gsfront/ekans.pic"
EkansPicBack::       INCBIN "gfx/pokemon/gsback/ekansb.pic"
ParasPicFront::      INCBIN "gfx/pokemon/gsfront/paras.pic"
ParasPicBack::       INCBIN "gfx/pokemon/gsback/parasb.pic"
PoliwhirlPicFront::  INCBIN "gfx/pokemon/gsfront/poliwhirl.pic"
PoliwhirlPicBack::   INCBIN "gfx/pokemon/gsback/poliwhirlb.pic"
PoliwrathPicFront::  INCBIN "gfx/pokemon/gsfront/poliwrath.pic"
PoliwrathPicBack::   INCBIN "gfx/pokemon/gsback/poliwrathb.pic"
WeedlePicFront::     INCBIN "gfx/pokemon/gsfront/weedle.pic"
WeedlePicBack::      INCBIN "gfx/pokemon/gsback/weedleb.pic"
KakunaPicFront::     INCBIN "gfx/pokemon/gsfront/kakuna.pic"
KakunaPicBack::      INCBIN "gfx/pokemon/gsback/kakunab.pic"
BeedrillPicFront::   INCBIN "gfx/pokemon/gsfront/beedrill.pic"
BeedrillPicBack::    INCBIN "gfx/pokemon/gsback/beedrillb.pic"
ENDC

IF !GEN_2_GRAPHICS
MoltresPicFront::    INCBIN "gfx/pokemon/front/moltres.pic"
MoltresPicBack::     INCBIN "gfx/pokemon/back/moltresb.pic"

TentacoolPicFront::  INCBIN "gfx/pokemon/front/tentacool.pic"
TentacoolPicBack::   INCBIN "gfx/pokemon/back/tentacoolb.pic"
ScytherPicFront::    INCBIN "gfx/pokemon/front/scyther.pic"
ScytherPicBack::     INCBIN "gfx/pokemon/back/scytherb.pic"
StaryuPicFront::     INCBIN "gfx/pokemon/front/staryu.pic"
StaryuPicBack::      INCBIN "gfx/pokemon/back/staryub.pic"
BlastoisePicFront::  INCBIN "gfx/pokemon/front/blastoise.pic"
BlastoisePicBack::   INCBIN "gfx/pokemon/back/blastoiseb.pic"
PinsirPicFront::     INCBIN "gfx/pokemon/front/pinsir.pic"
PinsirPicBack::      INCBIN "gfx/pokemon/back/pinsirb.pic"
TangelaPicFront::    INCBIN "gfx/pokemon/front/tangela.pic"
TangelaPicBack::     INCBIN "gfx/pokemon/back/tangelab.pic"

JolteonPicFront::    INCBIN "gfx/pokemon/front/jolteon.pic"
JolteonPicBack::     INCBIN "gfx/pokemon/back/jolteonb.pic"
VaporeonPicFront::   INCBIN "gfx/pokemon/front/vaporeon.pic"
VaporeonPicBack::    INCBIN "gfx/pokemon/back/vaporeonb.pic"
MachopPicFront::     INCBIN "gfx/pokemon/front/machop.pic"
MachopPicBack::      INCBIN "gfx/pokemon/back/machopb.pic"
ZubatPicFront::      INCBIN "gfx/pokemon/front/zubat.pic"
ZubatPicBack::       INCBIN "gfx/pokemon/back/zubatb.pic"
EkansPicFront::      INCBIN "gfx/pokemon/front/ekans.pic"
EkansPicBack::       INCBIN "gfx/pokemon/back/ekansb.pic"
ParasPicFront::      INCBIN "gfx/pokemon/front/paras.pic"
ParasPicBack::       INCBIN "gfx/pokemon/back/parasb.pic"
PoliwhirlPicFront::  INCBIN "gfx/pokemon/front/poliwhirl.pic"
PoliwhirlPicBack::   INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PoliwrathPicFront::  INCBIN "gfx/pokemon/front/poliwrath.pic"
PoliwrathPicBack::   INCBIN "gfx/pokemon/back/poliwrathb.pic"
WeedlePicFront::     INCBIN "gfx/pokemon/front/weedle.pic"
WeedlePicBack::      INCBIN "gfx/pokemon/back/weedleb.pic"
KakunaPicFront::     INCBIN "gfx/pokemon/front/kakuna.pic"
KakunaPicBack::      INCBIN "gfx/pokemon/back/kakunab.pic"
BeedrillPicFront::   INCBIN "gfx/pokemon/front/beedrill.pic"
BeedrillPicBack::    INCBIN "gfx/pokemon/back/beedrillb.pic"
ENDC


SECTION "Pics 2", ROMX

IF GEN_2_GRAPHICS
HaunterPicFront::    INCBIN "gfx/pokemon/gsfront/haunter.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/gsback/haunterb.pic"
AbraPicFront::       INCBIN "gfx/pokemon/gsfront/abra.pic"
AbraPicBack::        INCBIN "gfx/pokemon/gsback/abrab.pic"
AlakazamPicFront::   INCBIN "gfx/pokemon/gsfront/alakazam.pic"
AlakazamPicBack::    INCBIN "gfx/pokemon/gsback/alakazamb.pic"
PidgeottoPicFront::  INCBIN "gfx/pokemon/gsfront/pidgeotto.pic"
PidgeottoPicBack::   INCBIN "gfx/pokemon/gsback/pidgeottob.pic"
PidgeotPicFront::    INCBIN "gfx/pokemon/gsfront/pidgeot.pic"
PidgeotPicBack::     INCBIN "gfx/pokemon/gsback/pidgeotb.pic"
StarmiePicFront::    INCBIN "gfx/pokemon/gsfront/starmie.pic"
StarmiePicBack::     INCBIN "gfx/pokemon/gsback/starmieb.pic"
RedPicBack::         INCBIN "gfx/gstrainers/redb.pic"
OldManPicBack::      INCBIN "gfx/gstrainers/oldmanb.pic"

GastlyPicFront::     INCBIN "gfx/pokemon/gsfront/gastly.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/gsback/gastlyb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/gsfront/vileplume.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/gsback/vileplumeb.pic"
ENDC

IF !GEN_2_GRAPHICS
HaunterPicFront::    INCBIN "gfx/pokemon/front/haunter.pic"
HaunterPicBack::     INCBIN "gfx/pokemon/back/haunterb.pic"
AbraPicFront::       INCBIN "gfx/pokemon/front/abra.pic"
AbraPicBack::        INCBIN "gfx/pokemon/back/abrab.pic"
AlakazamPicFront::   INCBIN "gfx/pokemon/front/alakazam.pic"
AlakazamPicBack::    INCBIN "gfx/pokemon/back/alakazamb.pic"
PidgeottoPicFront::  INCBIN "gfx/pokemon/front/pidgeotto.pic"
PidgeottoPicBack::   INCBIN "gfx/pokemon/back/pidgeottob.pic"
PidgeotPicFront::    INCBIN "gfx/pokemon/front/pidgeot.pic"
PidgeotPicBack::     INCBIN "gfx/pokemon/back/pidgeotb.pic"
StarmiePicFront::    INCBIN "gfx/pokemon/front/starmie.pic"
StarmiePicBack::     INCBIN "gfx/pokemon/back/starmieb.pic"
RedPicBack::         INCBIN "gfx/player/redb.pic"
OldManPicBack::      INCBIN "gfx/battle/oldmanb.pic"

GastlyPicFront::     INCBIN "gfx/pokemon/front/gastly.pic"
GastlyPicBack::      INCBIN "gfx/pokemon/back/gastlyb.pic"
VileplumePicFront::  INCBIN "gfx/pokemon/front/vileplume.pic"
VileplumePicBack::   INCBIN "gfx/pokemon/back/vileplumeb.pic"
ENDC


SECTION "Pics 3", ROMX

ArticunoPicFront::    INCBIN "gfx/pokemon/front/articuno.pic"
ArticunoPicBack::     INCBIN "gfx/pokemon/back/articunob.pic"
ZapdosPicFront::      INCBIN "gfx/pokemon/front/zapdos.pic"
ZapdosPicBack::       INCBIN "gfx/pokemon/back/zapdosb.pic"
DittoPicFront::       INCBIN "gfx/pokemon/front/ditto.pic"
DittoPicBack::        INCBIN "gfx/pokemon/back/dittob.pic"
MeowthPicFront::      INCBIN "gfx/pokemon/front/meowth.pic"
MeowthPicBack::       INCBIN "gfx/pokemon/back/meowthb.pic"
KrabbyPicFront::      INCBIN "gfx/pokemon/front/krabby.pic"
KrabbyPicBack::       INCBIN "gfx/pokemon/back/krabbyb.pic"
VulpixPicFront::      INCBIN "gfx/pokemon/front/vulpix.pic"
VulpixPicBack::       INCBIN "gfx/pokemon/back/vulpixb.pic"
NinetalesPicFront::   INCBIN "gfx/pokemon/front/ninetales.pic"
NinetalesPicBack::    INCBIN "gfx/pokemon/back/ninetalesb.pic"
PikachuPicFront::     INCBIN "gfx/pokemon/front/pikachu.pic"
PikachuPicBack::      INCBIN "gfx/pokemon/back/pikachub.pic"
RaichuPicFront::      INCBIN "gfx/pokemon/front/raichu.pic"
RaichuPicBack::       INCBIN "gfx/pokemon/back/raichub.pic"
DratiniPicFront::     INCBIN "gfx/pokemon/front/dratini.pic"
DratiniPicBack::      INCBIN "gfx/pokemon/back/dratinib.pic"
DragonairPicFront::   INCBIN "gfx/pokemon/front/dragonair.pic"
DragonairPicBack::    INCBIN "gfx/pokemon/back/dragonairb.pic"
KabutoPicFront::      INCBIN "gfx/pokemon/front/kabuto.pic"
KabutoPicBack::       INCBIN "gfx/pokemon/back/kabutob.pic"
KabutopsPicFront::    INCBIN "gfx/pokemon/front/kabutops.pic"
KabutopsPicBack::     INCBIN "gfx/pokemon/back/kabutopsb.pic"
HorseaPicFront::      INCBIN "gfx/pokemon/front/horsea.pic"
HorseaPicBack::       INCBIN "gfx/pokemon/back/horseab.pic"
SeadraPicFront::      INCBIN "gfx/pokemon/front/seadra.pic"
SeadraPicBack::       INCBIN "gfx/pokemon/back/seadrab.pic"
SandshrewPicFront::   INCBIN "gfx/pokemon/front/sandshrew.pic"
SandshrewPicBack::    INCBIN "gfx/pokemon/back/sandshrewb.pic"
SandslashPicFront::   INCBIN "gfx/pokemon/front/sandslash.pic"
SandslashPicBack::    INCBIN "gfx/pokemon/back/sandslashb.pic"
OmanytePicFront::     INCBIN "gfx/pokemon/front/omanyte.pic"
OmanytePicBack::      INCBIN "gfx/pokemon/back/omanyteb.pic"
OmastarPicFront::     INCBIN "gfx/pokemon/front/omastar.pic"
OmastarPicBack::      INCBIN "gfx/pokemon/back/omastarb.pic"
JigglypuffPicFront::  INCBIN "gfx/pokemon/front/jigglypuff.pic"
JigglypuffPicBack::   INCBIN "gfx/pokemon/back/jigglypuffb.pic"
WigglytuffPicFront::  INCBIN "gfx/pokemon/front/wigglytuff.pic"
WigglytuffPicBack::   INCBIN "gfx/pokemon/back/wigglytuffb.pic"
EeveePicFront::       INCBIN "gfx/pokemon/front/eevee.pic"
EeveePicBack::        INCBIN "gfx/pokemon/back/eeveeb.pic"
FlareonPicFront::     INCBIN "gfx/pokemon/front/flareon.pic"
FlareonPicBack::      INCBIN "gfx/pokemon/back/flareonb.pic"
JolteonPicFront::     INCBIN "gfx/pokemon/front/jolteon.pic"
JolteonPicBack::      INCBIN "gfx/pokemon/back/jolteonb.pic"
VaporeonPicFront::    INCBIN "gfx/pokemon/front/vaporeon.pic"
VaporeonPicBack::     INCBIN "gfx/pokemon/back/vaporeonb.pic"
MachopPicFront::      INCBIN "gfx/pokemon/front/machop.pic"
MachopPicBack::       INCBIN "gfx/pokemon/back/machopb.pic"
ZubatPicFront::       INCBIN "gfx/pokemon/front/zubat.pic"
ZubatPicBack::        INCBIN "gfx/pokemon/back/zubatb.pic"
EkansPicFront::       INCBIN "gfx/pokemon/front/ekans.pic"
EkansPicBack::        INCBIN "gfx/pokemon/back/ekansb.pic"
ParasPicFront::       INCBIN "gfx/pokemon/front/paras.pic"
ParasPicBack::        INCBIN "gfx/pokemon/back/parasb.pic"
PoliwhirlPicFront::   INCBIN "gfx/pokemon/front/poliwhirl.pic"
PoliwhirlPicBack::    INCBIN "gfx/pokemon/back/poliwhirlb.pic"
PoliwrathPicFront::   INCBIN "gfx/pokemon/front/poliwrath.pic"
PoliwrathPicBack::    INCBIN "gfx/pokemon/back/poliwrathb.pic"
WeedlePicFront::      INCBIN "gfx/pokemon/front/weedle.pic"
WeedlePicBack::       INCBIN "gfx/pokemon/back/weedleb.pic"
KakunaPicFront::      INCBIN "gfx/pokemon/front/kakuna.pic"
KakunaPicBack::       INCBIN "gfx/pokemon/back/kakunab.pic"
BeedrillPicFront::    INCBIN "gfx/pokemon/front/beedrill.pic"
BeedrillPicBack::     INCBIN "gfx/pokemon/back/beedrillb.pic"
; Removed 'mon sprites from here


SECTION "Pics 4", ROMX

; Removed 'mon sprites from here


SECTION "Pics 5", ROMX

BulbasaurPicFront::    INCBIN "gfx/pokemon/front/bulbasaur.pic"
BulbasaurPicBack::     INCBIN "gfx/pokemon/back/bulbasaurb.pic"
VenusaurPicFront::     INCBIN "gfx/pokemon/front/venusaur.pic"
VenusaurPicBack::      INCBIN "gfx/pokemon/back/venusaurb.pic"
TentacruelPicFront::   INCBIN "gfx/pokemon/front/tentacruel.pic"
TentacruelPicBack::    INCBIN "gfx/pokemon/back/tentacruelb.pic"
GoldeenPicFront::      INCBIN "gfx/pokemon/front/goldeen.pic"
GoldeenPicBack::       INCBIN "gfx/pokemon/back/goldeenb.pic"
SeakingPicFront::      INCBIN "gfx/pokemon/front/seaking.pic"
SeakingPicBack::       INCBIN "gfx/pokemon/back/seakingb.pic"
PonytaPicFront::       INCBIN "gfx/pokemon/front/ponyta.pic"
RapidashPicFront::     INCBIN "gfx/pokemon/front/rapidash.pic"
PonytaPicBack::        INCBIN "gfx/pokemon/back/ponytab.pic"
RapidashPicBack::      INCBIN "gfx/pokemon/back/rapidashb.pic"
RattataPicFront::      INCBIN "gfx/pokemon/front/rattata.pic"
RattataPicBack::       INCBIN "gfx/pokemon/back/rattatab.pic"
RaticatePicFront::     INCBIN "gfx/pokemon/front/raticate.pic"
RaticatePicBack::      INCBIN "gfx/pokemon/back/raticateb.pic"
NidorinoPicFront::     INCBIN "gfx/pokemon/front/nidorino.pic"
NidorinoPicBack::      INCBIN "gfx/pokemon/back/nidorinob.pic"
NidorinaPicFront::     INCBIN "gfx/pokemon/front/nidorina.pic"
NidorinaPicBack::      INCBIN "gfx/pokemon/back/nidorinab.pic"
GeodudePicFront::      INCBIN "gfx/pokemon/front/geodude.pic"
GeodudePicBack::       INCBIN "gfx/pokemon/back/geodudeb.pic"
PorygonPicFront::      INCBIN "gfx/pokemon/front/porygon.pic"
PorygonPicBack::       INCBIN "gfx/pokemon/back/porygonb.pic"
AerodactylPicFront::   INCBIN "gfx/pokemon/front/aerodactyl.pic"
AerodactylPicBack::    INCBIN "gfx/pokemon/back/aerodactylb.pic"
MagnemitePicFront::    INCBIN "gfx/pokemon/front/magnemite.pic"
MagnemitePicBack::     INCBIN "gfx/pokemon/back/magnemiteb.pic"
CharmanderPicFront::   INCBIN "gfx/pokemon/front/charmander.pic"
CharmanderPicBack::    INCBIN "gfx/pokemon/back/charmanderb.pic"
SquirtlePicFront::     INCBIN "gfx/pokemon/front/squirtle.pic"
SquirtlePicBack::      INCBIN "gfx/pokemon/back/squirtleb.pic"
CharmeleonPicFront::   INCBIN "gfx/pokemon/front/charmeleon.pic"
CharmeleonPicBack::    INCBIN "gfx/pokemon/back/charmeleonb.pic"
WartortlePicFront::    INCBIN "gfx/pokemon/front/wartortle.pic"
WartortlePicBack::     INCBIN "gfx/pokemon/back/wartortleb.pic"
CharizardPicFront::    INCBIN "gfx/pokemon/front/charizard.pic"
CharizardPicBack::     INCBIN "gfx/pokemon/back/charizardb.pic"
OddishPicFront::       INCBIN "gfx/pokemon/front/oddish.pic"
OddishPicBack::        INCBIN "gfx/pokemon/back/oddishb.pic"
GloomPicFront::        INCBIN "gfx/pokemon/front/gloom.pic"
GloomPicBack::         INCBIN "gfx/pokemon/back/gloomb.pic"
VileplumePicFront::    INCBIN "gfx/pokemon/front/vileplume.pic"
VileplumePicBack::     INCBIN "gfx/pokemon/back/vileplumeb.pic"
BellsproutPicFront::   INCBIN "gfx/pokemon/front/bellsprout.pic"
BellsproutPicBack::    INCBIN "gfx/pokemon/back/bellsproutb.pic"
WeepinbellPicFront::   INCBIN "gfx/pokemon/front/weepinbell.pic"
WeepinbellPicBack::    INCBIN "gfx/pokemon/back/weepinbellb.pic"
VictreebelPicFront::   INCBIN "gfx/pokemon/front/victreebel.pic"
VictreebelPicBack::    INCBIN "gfx/pokemon/back/victreebelb.pic"
; Removed 'mon sprites from here


SECTION "Pics 6", ROMX

TrainerPics::
IF GEN_2_GRAPHICS
YoungsterPic::     INCBIN "gfx/gstrainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/gstrainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/gstrainers/lass.pic"
SailorPic::        INCBIN "gfx/gstrainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/gstrainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/gstrainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/gstrainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/gstrainers/supernerd.pic"
HikerPic::         INCBIN "gfx/gstrainers/hiker.pic"
BikerPic::         INCBIN "gfx/gstrainers/biker.pic"
BurglarPic::       INCBIN "gfx/gstrainers/burglar.pic"
EngineerPic::      INCBIN "gfx/gstrainers/engineer.pic"
FisherPic::        INCBIN "gfx/gstrainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/gstrainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/gstrainers/cueball.pic"
GamblerPic::       INCBIN "gfx/gstrainers/gambler.pic"
BeautyPic::        INCBIN "gfx/gstrainers/beauty.pic"
PsychicPic::       INCBIN "gfx/gstrainers/psychic.pic"
RockerPic::        INCBIN "gfx/gstrainers/rocker.pic"
JugglerPic::       INCBIN "gfx/gstrainers/juggler.pic"
TamerPic::         INCBIN "gfx/gstrainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/gstrainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/gstrainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/gstrainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/gstrainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/gstrainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/gstrainers/giovanni.pic"
RocketPic::        INCBIN "gfx/gstrainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/gstrainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/gstrainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/gstrainers/bruno.pic"
BrockPic::         INCBIN "gfx/gstrainers/brock.pic"
MistyPic::         INCBIN "gfx/gstrainers/misty.pic"
LtSurgePic::       INCBIN "gfx/gstrainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/gstrainers/erika.pic"
KogaPic::          INCBIN "gfx/gstrainers/koga.pic"
BlainePic::        INCBIN "gfx/gstrainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/gstrainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/gstrainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/gstrainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/gstrainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/gstrainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/gstrainers/channeler.pic"
AgathaPic::        INCBIN "gfx/gstrainers/agatha.pic"
LancePic::         INCBIN "gfx/gstrainers/lance.pic"
ENDC

IF !GEN_2_GRAPHICS
YoungsterPic::     INCBIN "gfx/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/trainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/engineer.pic"
FisherPic::        INCBIN "gfx/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/rocker.pic"
JugglerPic::       INCBIN "gfx/trainers/juggler.pic"
TamerPic::         INCBIN "gfx/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/giovanni.pic"
RocketPic::        INCBIN "gfx/trainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/trainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/bruno.pic"
BrockPic::         INCBIN "gfx/trainers/brock.pic"
MistyPic::         INCBIN "gfx/trainers/misty.pic"
LtSurgePic::       INCBIN "gfx/trainers/lt.surge.pic"
ErikaPic::         INCBIN "gfx/trainers/erika.pic"
KogaPic::          INCBIN "gfx/trainers/koga.pic"
BlainePic::        INCBIN "gfx/trainers/blaine.pic"
SabrinaPic::       INCBIN "gfx/trainers/sabrina.pic"
GentlemanPic::     INCBIN "gfx/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/lance.pic"

SECTION "Pics 7", ROMX

;CrobatPicFront::  INCBIN "gfx/pokemon/front/crobat.pic"
;CrobatPicBack::   INCBIN "gfx/pokemon/back/crobatb.pic"

FossilKabutopsPic::   INCBIN "gfx/pokemon/front/fossilkabutops.pic"
FossilAerodactylPic::  INCBIN "gfx/pokemon/front/fossilaerodactyl.pic"
GhostPic::             INCBIN "gfx/battle/ghost.pic"
ENDC
